sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
- docker pull selion/hub:1.0.0
- docker pull selion/node-chrome:1.0.0
- docker pull selion/node-firefox:1.0.0

script: mvn integration-test
